# Generated by Django 2.1.7 on 2019-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
